<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WebServiceProvider" targetNamespace="http://www.boomi.com/connector/wss" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.boomi.com/connector/wss" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="WebServiceProviderPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.boomi.com/connector/wss">
<xsd:include schemaLocation="RemoteFiles/xsd_1.xsd"/>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="getProductPrice">
    <wsdl:part element="tns:getProductPrice" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="getProductPriceResponse">
    <wsdl:part element="tns:getProductPriceResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="WebServiceProviderPortType">
    <wsdl:operation name="getProductPrice">
      <wsdl:input message="tns:getProductPrice"/>
      <wsdl:output message="tns:getProductPriceResponse"/>
    </wsdl:operation>

  </wsdl:portType>
  <wsdl:binding name="WebServiceProviderPortBinding" type="tns:WebServiceProviderPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getProductPrice">
      <soap:operation soapAction="getProductPrice"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WebServiceProvider">
    <wsdl:port binding="tns:WebServiceProviderPortBinding" name="WebServiceProviderPort">
      <soap:address location="https://connect.boomi.com/ws/soap"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>